feat(ci): ensure stable devshells in pc node
input-output-hk/partner-chains-smart-contracts pull request #101
Opened 2024-08-21 18:07 UTC by tgunnoe

This adds a step to remotely dispatch a partner-chains devshell build job with the current PR on smart-contracts in order to always ensure stable devshells there.

### Prereview checklist

- [ ] The [CHANGELOG.md](../blob/master/CHANGELOG.md) has been updated under the `# Unreleased` header using the appropriate sub-headings with links to the appropriate issues/PRs.
- [ ] All tests pass in CI
- [ ] PR was self-reviewed

2024-08-21 19:16 UTC, nrdxp commented on .github/workflows/ci.yml
> +          repository: input-output-hk/partner-chains
does this work as is? The checkout action uses the autogenerated github token by default, which only has access to the current repo (not any other repos in the org). You might need to use a different token here, one with access to the pc repo.

2024-08-21 19:17 UTC, tgunnoe commented on .github/workflows/ci.yml
> +          repository: input-output-hk/partner-chains
It worked on a previous run. does it need anything if the repo is public? I don't think so

2024-08-22 10:55 UTC, gilligan commented
I'm confused about what this is or what it aims to achieve? why are we checking out `partner-chains` ? I don't believe we should create a dependency in this direction

2024-08-22 11:21 UTC, tgunnoe commented
> I'm confused about what this is or what it aims to achieve? why are we checking out partner-chains ? I don't believe we should create a dependency in this direction

It's to prevent the scenarios last week when a merge here broke the devshells on partner-chains. To ensure changes wont break downstream shells

2024-08-22 13:29 UTC, gilligan requested changes
This basically introduces some sort of circular dependency between pcsc and pc - I really don't think this is the way we should be going at all.
We can have some local check to ensure that the devShell from pcsc has the mandatory tools in $PATH but nothing beyond that.
See https://github.com/input-output-hk/partner-chains-smart-contracts/blob/pc-redo-nix/nix/tests/test-shell.sh for a possible approach

2024-08-23 10:16 UTC, LGLO commented on .github/workflows/ci.yml
> +          nix flake lock --update-input trustless-sidechain \
In partner-chains repo I've renamed trustless-sidechain to smart-contracts. Hence if this PR has been merged, I would have broken the main workflow of a _dependency_.

2024-08-23 12:01 UTC, closed without merging