wip: remove iogx
input-output-hk/partner-chains-smart-contracts pull request #122
Opened 2024-09-17 20:29 UTC by tgunnoe

### Prereview checklist

- [ ] The [CHANGELOG.md](../blob/master/CHANGELOG.md) has been updated under the `# Unreleased` header using the appropriate sub-headings with links to the appropriate issues/PRs.
- [ ] All tests pass in CI
- [ ] PR was self-reviewed

2024-09-19 12:56 UTC, nrdxp commented on nix/checks.nix
> +  upToDatePlutusScriptCheck = pkgs.runCommand "up-to-date-plutus-scripts-check"
might be nice to have this in a seperate script, perhaps somewhere in nix/scripts?

2024-09-19 13:08 UTC, nrdxp commented on flake.nix
> +    nixpkgs.follows = "haskell-nix/nixpkgs";
nosys will instantiate nixpkgs for you if you call the input `pkgs`

2024-09-19 13:08 UTC, nrdxp commented on nix/outputs.nix
> +inputs' @ { self
perhaps we can remove the the prime here: `inputs'` -> `inputs`

2024-09-19 13:09 UTC, nrdxp commented on nix/outputs.nix
> +  pkgs = (((nixpkgs.legacyPackages.extend inputs'.haskell-nix.overlay).extend inputs'.iohk-nix.overlays.crypto).extend inputs'.iohk-nix.overlays.haskell-nix-extra).extend (
we can maybe clean this up by allowing nosys to instantiate nixpkgs and passing in overlays

2024-09-19 13:25 UTC, tgunnoe commented on nix/checks.nix
> +  upToDatePlutusScriptCheck = pkgs.runCommand "up-to-date-plutus-scripts-check"
Good idea. This is just a migration from how it was before (and legacy stuff from mlabs). And there's probably a non-nix way within the makefiles somewhere as well, so I'll just create a ticket to keep track of it.
In general, let scripts be useable outside of nix.

2024-09-19 13:28 UTC, nrdxp commented on nix/checks.nix
> +  upToDatePlutusScriptCheck = pkgs.runCommand "up-to-date-plutus-scripts-check"
yeah I saw it wasn't any better before the change, just nice to split up longer than a few lines to its own file

2024-09-19 13:46 UTC, tgunnoe commented on flake.nix
> +    nixpkgs.follows = "haskell-nix/nixpkgs";
but then we'd need to do it again anyways for the overlays below, right?

2024-09-19 14:52 UTC, tgunnoe commented
> Nix shell doesn't seem to provide cabal. Not sure if I'm missing something.
> 
> ```
> $ nix develop
> $ cabal
> bash: cabal: command not found
> ```

Thanks, looks like iogx provided that while it made its shells. I'll add the toolchains missing from there

2024-09-19 14:56 UTC, gilligan commented on nix/shells.nix
> +      (if stdenv.isDarwin
This could perhaps be an overlay where spago is overriden to be either the one or the other depending on system. That way the shell only cares about including spago?

2024-09-19 14:57 UTC, gilligan commented on nix/shells.nix
> +      nodePackages.node2nix
I think we don't need node2nix anymore do we?

2024-09-19 18:01 UTC, tgunnoe commented on nix/shells.nix
> +      (if stdenv.isDarwin
I don't understand, is that not what's happening this way? IIRC the spago from nixpkgs for aarch64-darwin worked differently than the one from this overlay. since the nixpkgs versions are built from source it obviously has aarch64-darwin available, though. It's quite a mess honestly. I'll check again.

2024-09-20 09:06 UTC, gilligan commented on nix/shells.nix
> +      (if stdenv.isDarwin
Little misunderstanding: that is indeed what is happening here. Maybe I just didn't do a great job explaining myself:

The way I see it is that the job of the shell expression is just to say that `spago` should be in the buildInputs. Making sure that spago works on different systems would be the job of some override in the flake.nix

Does that make more sense?

2024-09-20 10:07 UTC, kpinter-iohk commented
After pulling:
1. `cd offchain/ && make update-scripts` fails to generate `RawScripts.purs`. This is because for some reason `IO.withFile` doesn't handle Unicode anymore, and there are `›` and `∷` characters in the output it's supposed to write. Seems like there was some magic in the previous version that fixed this. I'm okay with replacing these characters with their non-unicode equivalents too (`>` and `::`).
2. After fixing the above issue with the use of non-Unicode chars, `make build` fails with this again: https://github.com/input-output-hk/partner-chains-smart-contracts/pull/98#issuecomment-2315917519

2024-09-23 12:16 UTC, tgunnoe commented
@kpinter-iohk can you to see if all of your shell/build tooling is functional now?

2024-09-23 16:59 UTC, tgunnoe commented on nix/shells.nix
> +      (if stdenv.isDarwin
done

2024-09-25 10:56 UTC, gilligan requested changes

2024-09-25 10:56 UTC, gilligan commented on nix/shells.nix
> +      haskellPackages
```
nix-repl> builtins.typeOf haskellPackages
"set"
```

You don't need or want to include this. This is a huge set containing all haskellPackages for whatever nixpkgs picks as the default version of `ghc`.

2024-09-25 13:52 UTC, kpinter-iohk approved these changes

2024-09-26 09:37 UTC, kpinter-iohk commented
I see that the CI broke because script sizes changed. I wanted to look into this locally, however `cabal build` now fails when trying to resolve dependencies:
```
$ cabal build --minimize-conflict-set
Warning: Requested index-state 2024-07-16T05:49:34Z is newer than
'hackage.haskell.org'! Falling back to older state (2024-07-16T05:41:59Z).
Resolving dependencies...
Error: cabal: Could not resolve dependencies:
[__0] trying: trustless-sidechain-6.1.0 (user goal)
[__1] next goal: plutus-tx (dependency of trustless-sidechain)
[__1] rejecting: plutus-tx-1.30.0.0, plutus-tx-1.29.0.0, plutus-tx-1.28.0.0
(constraint from project config
/home/.../partner-chains-smart-contracts/onchain/cabal.project requires
^>=1.27)
[__1] trying: plutus-tx-1.27.0.0
[__2] next goal: plutus-core (dependency of trustless-sidechain)
[__2] rejecting: plutus-core-1.30.0.0 (conflict: plutus-tx =>
plutus-core^>=1.27)
[__2] skipping: plutus-core-1.29.0.0, plutus-core-1.28.0.0 (has the same
characteristics that caused the previous version to fail: excluded by
constraint '^>=1.27' from 'plutus-tx')
[__2] trying: plutus-core-1.27.0.0
[__3] next goal: cardano-crypto-class (dependency of trustless-sidechain)
[__3] rejecting: cardano-crypto-class-2.1.5.0, cardano-crypto-class-2.1.4.0,
cardano-crypto-class-2.1.3.0, cardano-crypto-class-2.1.2.0 (conflict:
pkg-config package libblst-any, not found in the pkg-config database)
[__3] rejecting: cardano-crypto-class-2.1.1.0 (conflict: plutus-core =>
cardano-crypto-class^>=2.1.2)
[__3] skipping: cardano-crypto-class-2.1.0.2, cardano-crypto-class-2.1.0.1,
cardano-crypto-class-2.1.0.0, cardano-crypto-class-2.0.0.1,
cardano-crypto-class-2.0.0.0.1, cardano-crypto-class-2.0.0 (has the same
characteristics that caused the previous version to fail: excluded by
constraint '^>=2.1.2' from 'plutus-core')
[__3] fail (backjumping, conflict set: cardano-crypto-class, plutus-core,
trustless-sidechain)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: plutus-tx, plutus-core,
cardano-crypto-class, trustless-sidechain
```

2024-09-27 10:41 UTC, kpinter-iohk commented on nix/outputs.nix
> -          moreutils
`moreutils` is needed by release.sh

2024-10-01 07:08 UTC, kpinter-iohk approved these changes
:tada: :1st_place_medal:

2024-10-01 12:12 UTC, merged