Reduce dependencies on CTL and flake.lock size
input-output-hk/partner-chains-smart-contracts pull request #87
Opened 2024-08-09 03:32 UTC by tgunnoe

### Prereview checklist

- [ ] The [CHANGELOG.md](../blob/master/CHANGELOG.md) has been updated under the `# Unreleased` header using the appropriate sub-headings with links to the appropriate issues/PRs.
- [ ] All tests pass in CI
- [ ] PR was self-reviewed

2024-08-09 09:22 UTC, gilligan requested changes
Most of the PR seems to be about changing where our dependencies come from and detaching things a bit more from CTL. 

If you could please first split off the the change for getting the darwin build to work so we can get those builds to pass again. Everything else can follow later

2024-08-09 09:22 UTC, gilligan commented on .github/workflows/ci.yml
> +          npm install @esbuild/darwin-arm64
Hm, can you explain what is happening? We need to explicitly install the darwin-arm64 binary of esbuild and then it works? Do you know _why_ ?

The `esbuild` dependency should just pick the right binary on its own

2024-08-09 19:29 UTC, tgunnoe commented on .github/workflows/ci.yml
> +          npm install @esbuild/darwin-arm64
Because you can't fetch external artifacts while in the nix sandbox. esbuild see's that this is not a typical architecture, so it tries to correct that (dumb nodejs). 
In the future, we can replace this fix with a 2nix node solution that has overrides in mind for things like this, but I think a patch will work for now.

2024-08-09 19:30 UTC, tgunnoe commented
> Is the scope of this PR in that case actually as small as it could be? Only the esbuild change is unrelated to everything else?

I moved the other stuff to a separate PR: https://github.com/input-output-hk/partner-chains-smart-contracts/pull/89 but I would recommend merging that one, in addition to this one, for the release

2024-08-12 06:06 UTC, LGLO commented on flake.nix
> +    blank.url = "github:input-output-hk/empty-flake";
Is there any documentation for this trick? Could you point in a comment why this thing exists?

2024-08-12 07:08 UTC, gilligan approved these changes

2024-08-12 07:08 UTC, merged

2024-08-12 12:04 UTC, tgunnoe commented on flake.nix
> +    blank.url = "github:input-output-hk/empty-flake";
because there's no real way using flakes to bring in only parts of a flake that you actually use. for example, in the CTL we don't want to bring in 15 versions of their stack (along with the ones we use) that they use in testing. We ideally want to say "use this version of <dep> for everything in the stack, but that doesn't exist.
here's a followup PR which utilizes that more extensively https://github.com/input-output-hk/partner-chains-smart-contracts/pull/89